apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mentorbot
  namespace: mentorbot
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  rules:
    - host: mentorbot.aiklox.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mentorbot
                port:
                  name: http
  tls:
    - hosts:
        - mentorbot.aiklox.com
      secretName: aiklox-tls

